from django.db import models
#from api.fields import JSONField

# Create your models here.

class Campaign(models.Model):
    #category = models.ForeignKey(Category, on_delete=models.PROTECT)
    campaign_id = models.IntegerField(primary_key=True)
    url = models.TextField()
    auto_fb_post_mode = models.BooleanField()
    collected_date = models.TextField()
    category_id = models.IntegerField()
    category = models.TextField()
    currencycode = models.TextField()
    current_amount = models.IntegerField()
    goal = models.IntegerField()
    donators = models.IntegerField()
    days_active = models.IntegerField()
    days_created = models.IntegerField()
    title = models.TextField()
    description = models.TextField()
    default_url = models.TextField()
    has_beneficiary = models.BooleanField()
    media_type = models.IntegerField()
    project_type = models.IntegerField()
    turn_off_donations = models.BooleanField()
    user_id = models.IntegerField()
    user_first_name = models.TextField()
    user_last_name = models.TextField()
    user_facebook_id = models.TextField()
    user_profile_url = models.TextField()
    visible_in_search = models.BooleanField()
    status = models.IntegerField()
    deactivated = models.BooleanField()
    state = models.TextField()
    is_launched = models.BooleanField()
    campaign_image_url = models.TextField()
    created_at = models.TextField()
    launch_date = models.TextField()
    campaign_hearts = models.IntegerField()
    social_share_total = models.IntegerField()
    social_share_last_update = models.TextField()
    location_city = models.TextField()
    location_country = models.TextField()
    location_zip = models.TextField()
    is_charity = models.BooleanField()
    charity_valid = models.BooleanField()
    charity_npo_id = models.IntegerField()
    charity_name = models.TextField()
    velocity = models.IntegerField()
    